# Generated by Django 2.1.1 on 2019-09-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('is_done', 'DONE'), ('is_todo', 'TODO'), ('is_tested', 'TESTED')], max_length=20)),
            ],
        ),
    ]
