# Generated by Django 2.1.1 on 2019-10-29 08:45

from django.db import migrations, models
import utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.upload.task_document_path),
        ),
    ]
