# Generated by Django 2.1.1 on 2019-09-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190925_0948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='my_tasks',
        ),
    ]
