# Generated by Django 2.1.1 on 2019-10-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')], default=2),
        ),
    ]
