
TASK_DONE = 1
TASK_TODO = 2
TASK_TESTED = 3
TASK_STATUSES = (
    (TASK_DONE, 'DONE'),
    (TASK_TODO, 'TODO'),
    (TASK_TESTED, 'TESTED'),
)

TASK_PRIORITY_LOW = 1
TASK_PRIORITY_MEDIUM = 2
TASK_PRIORITY_HIGH = 3
TASK_PRIORITIES = (
    (TASK_PRIORITY_LOW, 'low'),
    (TASK_PRIORITY_MEDIUM, 'medium'),
    (TASK_PRIORITY_HIGH, 'high'),
)