# Generated by Django 2.1.1 on 2019-09-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190925_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('name', 'status'), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'name')},
        ),
    ]
