# Generated by Django 2.1.1 on 2019-10-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': (('-name',), 'desc'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-name',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MyTask',
        ),
        migrations.AlterUniqueTogether(
            name='developertask',
            unique_together={('name', 'desc')},
        ),
    ]
