# Generated by Django 2.1.1 on 2019-10-29 09:00

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_task_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.upload.task_document_path, validators=[utils.validators.validate_file_size, utils.validators.validate_extension]),
        ),
    ]
